### ISSUE TITLE
cluster_name not populated in cassandra.yaml by k8ssandra-client

### ISSUE THREAD

**Issue by dnugmanov** [k8ssandra/k8ssandra-client#17]
**Issue Description:**

I've noticed that the `k8ssandra-client` does not fill the `cluster_name` field in `cassandra.yaml`. The `ClusterInfo` struct contains a field for the cluster name, but it doesn't seem to be used anywhere in the code. This leads to incorrect monitoring metrics from the exporter because it fills the `cluster_name` label according to the `cassandra.yaml` parameters.

**Example:**

```yaml
❯ cassandra@damir-test-damir-test-dc-rack1-sts-0:/$ cat /etc/cassandra/cassandra.yaml | grep cluster_name
cluster_name: Test Cluster

❯ k get pods -n mynamespace -o yaml | grep CONFIG_FILE_DATA -A 1
  - name: CONFIG_FILE_DATA
    value: '{"cassandra-env-sh":{"___OMITTED:___"cluster-info":{"name":"damir-test","seeds":"damir-test-seed-service,damir-test-damir-test-dc-additional-seed-service"},___OMITTED:___}'
```

**Expected Behavior:**

I believe the cluster_name field in cassandra.yaml should be properly filled by the k8ssandra_client.

**Additional Information:**

k8ssandra-client version: v0.2.0
